### ISSUE TITLE
Update `matting_tutorial.ipynb`

### ISSUE THREAD

**Issue by bottledmind** [open-mmlab/mmagic#1179]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmediting/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmediting).

### 🐞 Describe the bug

Hey, guys, you need to update at least `demo/matting_tutorial.ipynb`. It throws errors on inference with these https://github.com/open-mmlab/mmediting/issues/962 logs

### Environment

Current colab versions
![image](https://user-images.githubusercontent.com/60937565/193297387-3f31a15a-e937-4874-945c-d46f45835c0b.png)
Tried mmcv: 1.6.2, 1.5.0, 1.4.8, 1.4.7

**Comment by zengyh1900** [comment]
@Z-Fran Please check this issue and also https://github.com/open-mmlab/mmediting/issues/962

**Comment by Z-Fran** [comment]
Sorry for the late reply. I have succeeded to run `matting_tutorial.ipynb` in the environment `torch 1.8.0+cu101,  mmcv(mmcv-full) 1.6.2, MMEditing 0.15.2`. Can you supply more information?

**Comment by bottledmind** [comment]
@Z-Fran What info do you need specifically?
I'm running `matting_tutorial.ipynb` inside Google Colaboratory.

Default colab environment:
- torch==1.12.1+cu113
- torchvision==0.13.1+cu113

Installed with mim:
- mmcv-full==1.6.2

Installed from source:
- mmedit==0.15.2

Running `pred_alpha = matting_inference(model, merged_path, trimap_path) * 255` got me 
```python
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-10-52723053bd50>](https://localhost:8080/#) in <module>
      1 # Use the mattor to do inference
----> 2 pred_alpha = matting_inference(model, merged_path, trimap_path) * 255

4 frames

[/content/mmediting/mmedit/apis/matting_inference.py](https://localhost:8080/#) in matting_inference(model, img, trimap)
     74     # forward the model
     75     with torch.no_grad():
---> 76         result = model(test_mode=True, **data)
     77 
     78     return result['pred_alpha']

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

[/content/mmediting/mmedit/models/mattors/base_mattor.py](https://localhost:8080/#) in forward(self, merged, trimap, meta, alpha, test_mode, **kwargs)
    261         """
    262         if test_mode:
--> 263             return self.forward_test(merged, trimap, meta, **kwargs)
    264 
    265         return self.forward_train(merged, trimap, meta, alpha, **kwargs)

[/content/mmediting/mmedit/models/mattors/indexnet.py](https://localhost:8080/#) in forward_test(self, merged, trimap, meta, save_image, save_path, iteration)
    107 
    108         pred_alpha = pred_alpha.cpu().numpy().squeeze()
--> 109         pred_alpha = self.restore_shape(pred_alpha, meta)
    110         eval_result = self.evaluate(pred_alpha, meta)
    111 

[/content/mmediting/mmedit/models/mattors/base_mattor.py](https://localhost:8080/#) in restore_shape(self, pred_alpha, meta)
    128             np.ndarray: The reshaped predicted alpha.
    129         """
--> 130         ori_trimap = meta[0]['ori_trimap'].squeeze()
    131         ori_h, ori_w = meta[0]['merged_ori_shape'][:2]
    132 

TypeError: 'DataContainer' object is not subscriptable
```

**Comment by bottledmind** [comment]
> Sorry for the late reply. I have succeeded to run `matting_tutorial.ipynb` in the environment `torch 1.8.0+cu101, mmcv(mmcv-full) 1.6.2, MMEditing 0.15.2`. Can you supply more information?

I've installed your torch version to colab with `pip install torch==1.8.0+cu101 torchvision==0.9.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`
Got in total:
- torch==1.8.0+cu101
- torchvision==0.9.0+cu101
- mmcv-full==1.6.2
- mmedit==0.15.2

Still got the same `TypeError: 'DataContainer' object is not subscriptable`

**Comment by bottledmind** [comment]
`mmedit.apis.matting_inference` is incompatible with later `mmcv` versions because of following line
https://github.com/open-mmlab/mmediting/blob/14f1ffc7740aff1769a37ad093c8a13f64da9448/mmedit/apis/matting_inference.py#L71
`collate` returnes a dict with "meta":`DataContainer`
Adding `data['meta'] = data['meta'].data[0]` solves the issue, but it seems to be a wrong and unorthodox way of fixing the issue. 
I'd rather say, `base_mattor.py` needs to be adjusted to use `DataContainer`

**Comment by Z-Fran** [comment]
It looks like some bugs in colab? Because I can run `pred_alpha = matting_inference(model, merged_path, trimap_path) * 255` successfully on my PC. Returns of  `data = collate([data], samples_per_gpu=1) ` are:
![screenshot-20221014-174638](https://user-images.githubusercontent.com/49083766/195817453-bd17cb27-81df-4224-8bc1-263f2bb11d4d.png)

**Comment by bottledmind** [comment]
@Z-Fran I've figured it out
`model = init_model(config, checkpoint, device='cuda')` works, but `model = init_model(config, checkpoint, device='cpu')` does not
Could you please make the code CPU compatible or make the notebook start in colab with GPU by default?
