### ISSUE TITLE
[Feature] Move Ops of StyleGAN3 to mmcv

### ISSUE THREAD

**Issue by zengyh1900** [open-mmlab/mmagic#1246]
### What is the problem this feature will solve?

Move Ops of StyleGAN3 to mmcv

### What is the feature?

Move Ops of StyleGAN3 to mmcv
https://github.com/open-mmlab/mmcv/pull/2290

**Comment by plyfager** [comment]
In MMCV: https://github.com/open-mmlab/mmcv/pull/2290
