### ISSUE TITLE
[Feature] Add Typehint for MMEditing-1.x

### ISSUE THREAD

**Issue by LeoXing1996** [open-mmlab/mmagic#1394]
### What's the feature?

MMEditing-1. x will be released soon, and we are adding type hints to MMRotate-1.x now, PRs from the community are welcome. You can refer to [mmdet](https://github.com/open-mmlab/mmdetection/tree/dev-3.x/docs).
To make the community fully aware of the progress, we list the progress here.
*Please feel free to leave a message and create a PR if you are willing to participate in any one of the file.**

**Part A**
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/apis/gan_inference.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/apis/inference.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/apis/inpainting_inference.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/apis/matting_inference.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/apis/restoration_face_inference.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/apis/restoration_inference.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/apis/restoration_video_inference.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/apis/translation_inference.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/apis/translation_inference.py

**Part B** 
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/aspp.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/downsample.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/ensemble.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/gated_conv_module.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/img_normalize.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/linear_module.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/multi_layer_disc.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/patch_disc.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/resnet.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/separable_conv_module.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/simple_encoder_decoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/smpatch_disc.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/sr_backbone.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/upsample.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_archs/vgg.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_models/base_edit_model.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_models/base_mattor.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_models/basic_interpolator.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_models/one_stage.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/base_models/two_stage.py

**Part C**
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/clip_loss.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/composition_loss.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/face_id_loss.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/feature_loss.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/gan_loss.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/gradient_loss.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/loss_wrapper.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/perceptual_loss.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/pixelwise_loss.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/loss_comps/clip_loss_comps.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/loss_comps/disc_auxiliary_loss_comps.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/loss_comps/face_id_loss_comps.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/loss_comps/gan_loss_comps.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/losses/loss_comps/gen_auxiliary_loss_comps.py

**Part D**
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/functional/fid_inception.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/functional/gaussian_funcs.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/functional/inception_utils.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/metrics/connectivity_error.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/metrics/gradient_error.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/metrics/matting_mse.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/metrics/metrics_utils.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/metrics/swd.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/metrics/sad.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/metrics/precision_and_recall.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/metrics/mse.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/metrics/ms_ssim.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/evaluation/metrics/ppl.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/utils/bbox_utils.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/utils/flow_warp.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/utils/model_utils.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/utils/tensor_utils.py

**Part E**
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/aotgan/aot_decoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/aotgan/aot_encoder_decoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/aotgan/aot_inpaintor.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/aotgan/aot_neck.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/arcface/arcface_modules.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/arcface/id_loss.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/arcface/model_irse.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/basicvsr/basicvsr.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/basicvsr/basicvsr_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/basicvsr_plusplus_net/basicvsr_plusplus_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/cain/cain.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/cain/cain_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/deepfillv1/contextual_attention.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/deepfillv1/contextual_attention_neck.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/deepfillv1/deepfill_decoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/deepfillv1/deepfill_disc.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/deepfillv1/deepfill_encoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/deepfillv1/deepfill_refiner.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/deepfillv1/deepfillv1.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/deepfillv2/two_stage_encoder_decoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/dic/dic.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/dic/dic_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/dic/feedback_hour_glass.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/dic/light_cnn.py

**Part F**
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/dim/dim.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/duf/duf.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/edsr/edsr_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/edvr/edvr.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/edvr/edvr_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/fba/fba_decoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/fba/fba_encoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/flavr/flavr.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/flavr/flavr_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/gca/gca.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/gca/gca_module.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/gca/resgca_dec.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/gca/resgca_enc.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/glean/glean_styleganv2.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/global_local/gl_decoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/global_local/gl_dilation.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/global_local/gl_disc.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/global_local/gl_encoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/global_local/gl_encoder_decoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/global_local/gl_inpaintor.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/iconvsr/iconvsr_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/indexnet/indexnet.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/indexnet/indexnet_decoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/indexnet/indexnet_encoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/liif/liif.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/liif/liif_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/liif/mlp_refiner.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/pconv/mask_conv_module.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/pconv/partial_conv.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/pconv/pconv_decoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/pconv/pconv_encoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/pconv/pconv_encoder_decoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/pconv/pconv_inpaintor.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/plain/plain_decoder.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/plain/plain_refiner.py

**Part G**
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/rdn/rdn_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/real_basicvsr/real_basicvsr.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/real_basicvsr/real_basicvsr_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/real_esrgan/real_esrgan.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/real_esrgan/unet_disc.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/srcnn/srcnn_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/srgan/modified_vgg.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/srgan/sr_resnet.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/srgan/srgan.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/tdan/tdan.py
- [ ] #1395
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/tof/tof_vfi_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/tof/tof_vsr_net.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/ttsr/lte.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/ttsr/search_transformer.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/ttsr/ttsr.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/ttsr/ttsr_disc.py
- [ ] https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/ttsr/ttsr_net.py

**Comment by liangzelong** [comment]
梁泽龙 type hints partC

**Comment by xiaomile** [comment]
麦梓超 type hints partB
