### ISSUE TITLE
Roadmap of MMEditing

### ISSUE THREAD

**Issue by zengyh1900** [open-mmlab/mmagic#1412]
We keep this issue open to **collect and release** feature requests from our community and hear your voice. 
Our monthly release plan will be updated in different issues.

In this issue, you can either:

1. Suggest a new feature by leaving a comment.
2. Vote for a feature request with 👍 or be against with 👎. (Remember that developers are busy and cannot respond to all feature requests, so vote for your most favorable one!)
3. Tell us that you would like to help implement one of the features in the list or review the PRs. (This is the greatest things to hear about!)

We also released our TODO list on the [project page](https://github.com/orgs/open-mmlab/projects/9/views/6). Most of the TODO items are described in their corresponding issues with detailed requirement documentation. Once you make a pull request for a specific TODO item, maintainers will help to improve and merge it.

Feel free to leave a message in the issue of any item and create a PR if you are interested in any of the item.

**Comment by www516717402** [comment]
Suggest some prohect about add audio driven talking face .
