### ISSUE TITLE
[New Models] SR+obejet detection. such as eesrgan

### ISSUE THREAD

**Issue by roileaner** [open-mmlab/mmagic#1709]
### Model/Dataset/Scheduler description

please add some models about SR+obejet detection. such as eesrgan..

### Open source status

- [√] The model implementation is available
- [√] The model weights are available.

### Provide useful links for the implementation
https://github.com/Jakaria08/EESRGAN

**Comment by Z-Fran** [comment]
We will not consider supporting it because it's lower priority. We can give you some help to add it to projects if you are willing.
