### ISSUE TITLE
Poor quality image inpainting 

### ISSUE THREAD

**Issue by asideras** [open-mmlab/mmagic#1789]
Hello everyone, congratulations on your great work.

I am attempting to use a pre-trained model to perform image inpainting on my own images. However, I am obtaining poor results for multiple images. Below, you can see the masked image, the mask, the output, and the code I executed:

![Places365_val_00000012_masked](https://user-images.githubusercontent.com/22640301/233831618-dcb84f65-98b1-4277-b235-e4434151ac0f.jpg)
![Places365_val_00000012_mask](https://user-images.githubusercontent.com/22640301/233831621-bea4498f-0c32-4a9e-9796-8ef95e6d0d67.jpg)
![result](https://user-images.githubusercontent.com/22640301/233831625-233b424b-5e3f-4dca-99b9-cb4619c3c684.png)

`!python demo/inpainting_demo.py \
    configs/deepfillv2/deepfillv2_8xb2_places-256x256.py \
    https://download.openmmlab.com/mmediting/inpainting/deepfillv2/deepfillv2_256x256_8x2_places_20200619-10d15793.pth \
    tests/data/inpainting/Places365_val_00000012_masked.jpg \
    tests/data/inpainting/Places365_val_00000012_mask.jpg \
    tests/data/pred/RES.png`
    
What did I do wrong?

Also, later on, I would like to run the model on multiple images (a subset of Places365) and use my own masks. Is this possible?
Thanks in advance.

**Comment by Z-Fran** [comment]
Closing this issue since the bug has been fixed in a merged pull request. Please feel free to reopen it if it has not been fixed.
