### ISSUE TITLE
AttributeError: 'EditDataSample' object has no attribute 'box_info'

### ISSUE THREAD

**Issue by Miky9527** [open-mmlab/mmagic#1795]
when i run inst_colorization_demo, the error 'EditDataSample' object has no attribute 'box_info'  appears. what should i do ? it seems like a code error instead of environment.

**Comment by Z-Fran** [comment]
We will fix this bug soon. @Miky9527

**Comment by Z-Fran** [comment]
This pr https://github.com/open-mmlab/mmagic/pull/1828 fix the bug. And you should run 'python demo/mmagic_inference_demo.py --model-name inst_colorization --img input.png --result-out-dir output.png'

**Comment by Z-Fran** [comment]
Closing this issue since the bug has been fixed in a merged pull request. Please feel free to reopen it if it has not been fixed.
