### ISSUE TITLE
ModuleNotFoundError: No module named 'controlnet_aux'

### ISSUE THREAD

**Issue by PotentialX** [open-mmlab/mmagic#1816]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

mmagic环境安装完成， mmagic.__version__返回 1.0 
但是无法发现controlnet_aux, 在github使用 search in this repository也没发现

### Reproduces the problem - code sample

主分支下，安装mmagic之后
python -c "from mmagic.apis import MMagicInferencer" 
即可发现报错

### Reproduces the problem - command or script

python -c "from mmagic.apis import MMagicInferencer" 

### Reproduces the problem - error message

mmagic/mmagic/apis/inferencers/controlnet_animation_inferencer.py", line 11, in <module>
    from controlnet_aux import HEDdetector
ModuleNotFoundError: No module named 'controlnet_aux'

**Comment by zwx8981** [comment]
Same issue, any update?

**Comment by liuwenran** [comment]
what about install it manually?
```shell
pip install controlnet_aux
```

**Comment by zwx8981** [comment]
@liuwenran It works, thanks!

**Comment by PotentialX** [comment]
@liuwenran  thx!

**Comment by camoody1** [comment]
> pip install controlnet_aux

Where do I run this command? I'm running a Windows portable installation of ComfyUI.
