### ISSUE TITLE
[Bug] The official example reported an error

### ISSUE THREAD

**Issue by bobo0810** [open-mmlab/mmagic#1825]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

sys.platform: linux
Python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) [GCC 9.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.55
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.11.0a0+17540c5
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.3.3 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS=-fno-gnu-unique -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0a0
OpenCV: 4.2.0
MMEngine: 0.7.2
MMCV: 2.0.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.6
MMagic: 1.0.0+c24769f

### Reproduces the problem - code sample
 ```python
from mmagic.apis import MMagicInferencer

sd_inferencer = MMagicInferencer(model_name="stable_diffusion")
text_prompts = "A panda is having dinner at KFC"
result_out_dir = "output/sd_res.png"
sd_inferencer.infer(text=text_prompts, result_out_dir=result_out_dir)
 ```
### Reproduces the problem - command or script
 ```python
from mmagic.apis import MMagicInferencer

sd_inferencer = MMagicInferencer(model_name="stable_diffusion")
text_prompts = "A panda is having dinner at KFC"
result_out_dir = "output/sd_res.png"
sd_inferencer.infer(text=text_prompts, result_out_dir=result_out_dir)
```
### Reproduces the problem - error message

![image](https://user-images.githubusercontent.com/26057879/234874818-4e1f5fe2-ef29-4c54-bf24-0a407f4618da.png)

**Comment by bobo0810** [comment]
diffusers                         0.16.0
transformers                      4.22.1

**Comment by Z-Fran** [comment]
please update transformers: such as `pip install transformers==4.27.4` @bobo0810

**Comment by Z-Fran** [comment]
Closing this issue since the bug has been fixed in a merged pull request. Please feel free to reopen it if it has not been fixed.

**Comment by bobo0810** [comment]
The same error is reported after installing the following dependencies

`pip install accelerate`

**Comment by bobo0810** [comment]
> 
An error occurs after the accelerate package is installed. The system runs normally after uninstallation

![image](https://github.com/open-mmlab/mmagic/assets/26057879/0743d7bc-51d1-4663-a63d-20ee4e4df9ab)

**Comment by Z-Fran** [comment]
![image](https://github.com/open-mmlab/mmagic/assets/49083766/8a3b5f22-646f-472c-aaa8-ada9a6aeea85)
This warning means it can't import diffusers, please check it. @bobo0810
