### ISSUE TITLE
[Bug] matting issue

### ISSUE THREAD

**Issue by mxgbs** [open-mmlab/mmagic#1835]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

pip
cuda 11.3

### Reproduces the problem - code sample

 python mmagic_inference_demo.py --model-name gca --img image_jpg/2010.jpg --tri_map tri_labels_dilate/2010.png --result-out-dir hair_mat/2010.png

### Reproduces the problem - command or script

 python mmagic_inference_demo.py --model-name gca --img image_jpg/2010.jpg --tri_map tri_labels_dilate/2010.png --result-out-dir hair_mat/2010.png

### Reproduces the problem - error message

open-mmlab/lib/python3.9/site-packages/mmengine/fileio/backends/local_backend.py", line 33, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'None'

### Additional information

Seems matting not working?
Do u only support gca for current framework? Can we add indexnet matting also? Thank you

**Comment by Z-Fran** [comment]
We have fixed this bug and support all models @ https://github.com/open-mmlab/mmagic/pull/1833

**Comment by Z-Fran** [comment]
Closing this issue since the bug has been fixed in a merged pull request. Please feel free to reopen it if it has not been fixed.
