### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 944284742** [open-mmlab/mmagic#1861]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

ubuntu18.04  cuda11.1

### Reproduces the problem - code sample

from mmagic.apis import MMagicInferencer

# Create a MMEdit instance and infer
editor = MMagicInferencer(model_name='controlnet_animation')

prompt = 'a girl, black hair, T-shirt, smoking, best quality, extremely detailed'
negative_prompt = 'longbody, lowres, bad anatomy, bad hands, missing fingers, ' + \
                  'extra digit, fewer digits, cropped, worst quality, low quality'

# you can download the example video with this link
# https://user-images.githubusercontent.com/12782558/227418400-80ad9123-7f8e-4c1a-8e19-0892ebad2a4f.mp4
video = '/path/to/your/input/video.mp4'
save_path = '/path/to/your/output/video.mp4'

# Do the inference to get result
editor.infer(video=video, prompt=prompt, negative_prompt=negative_prompt, save_path=save_path)

### Reproduces the problem - command or script

python demo.py

### Reproduces the problem - error message

My GPU has 24 gigabytes of video memory, but I ran out of video memory when running configs/controlnet_animation/anythingv3_config.py.

Then I adjusted it
editor.infer(video=video, prompt=prompt, negative_prompt=negative_prompt, save_path=save_path) has an input size of 256x256, and can then run. But the effect is very poor, mainly have the following questions:

The default 512x512 running model requires at least a large GPU.
Is it normal to imagine that the effect is poor after modifying the video input parameters to 256x256?

### Additional information

1.The default 512x512 running model requires at least a large GPU.
2.Is it normal to imagine that the effect is poor after modifying the video input parameters to 256x256?

**Comment by liuwenran** [comment]
duplicated with #1856
