### ISSUE TITLE
[Feature] Add Albumentation capabilities to the dataset pipeline

### ISSUE THREAD

**Issue by gvalvano** [open-mmlab/mmagic#1863]
### What's the feature?

In MMDetection, it is possible to use Albumentations to make complex transformations to the input data (reference [here](https://mmdetection.readthedocs.io/en/v2.18.0/_modules/mmdet/datasets/pipelines/transforms.html?highlight=albumentation) and [here](https://mmdetection.readthedocs.io/en/v2.18.0/api.html?highlight=albumentation#mmdet.datasets.pipelines.Albu)). 

Since fine-tuning generative models on small datasets could be problematic (e.g. dreambooth), I believe it would be extra-useful to add albumentation support in MMagic, too! This way, the user could artificially generate new data samples of the target concept.

### Any other context?

Example of config file with albumentation:

```python
albu_transforms = [
    dict(
        type='ShiftScaleRotate',
        shift_limit=0.0625,
        scale_limit=0.0,
        rotate_limit=0,
        interpolation=1,
        p=0.5),
    dict(
        type='RandomBrightnessContrast',
        brightness_limit=[0.1, 0.3],
        contrast_limit=[0.1, 0.3],
        p=0.2),),
]
train_pipeline = [
    dict(type='LoadImageFromFile', key='img', channel_order='rgb'),
    dict(type='Resize', scale=(512, 512)),
    dict(type='Albu', transforms=albu_transforms),
    dict(type='PackInputs')
]
```

**Comment by Z-Fran** [comment]
we will support a simple Albumentation there. https://github.com/open-mmlab/mmagic/pull/1894
