### ISSUE TITLE
[Bug] The variable image here is not used?

### ISSUE THREAD

**Issue by XDUWQ** [open-mmlab/mmagic#1866]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

In the code of `dreambooth` , the line https://github.com/open-mmlab/mmagic/blob/97f8a9b7a22dea71e629ba851d9d09aa9264dae5/mmagic/models/editors/dreambooth/dreambooth.py#LL259C13-L259C18 
The `image` variable in this line is not used later, although it can be used, it may not be reasonable.

### Reproduces the problem - code sample

In the code of `dreambooth` , the line https://github.com/open-mmlab/mmagic/blob/97f8a9b7a22dea71e629ba851d9d09aa9264dae5/mmagic/models/editors/dreambooth/dreambooth.py#LL259C13-L259C18 
The `image` variable in this line is not used later, although it can be used, it may not be reasonable.

### Reproduces the problem - command or script

In the code of `dreambooth` , the line https://github.com/open-mmlab/mmagic/blob/97f8a9b7a22dea71e629ba851d9d09aa9264dae5/mmagic/models/editors/dreambooth/dreambooth.py#LL259C13-L259C18 
The `image` variable in this line is not used later, although it can be used, it may not be reasonable.

### Reproduces the problem - error message

In the code of `dreambooth` , the line https://github.com/open-mmlab/mmagic/blob/97f8a9b7a22dea71e629ba851d9d09aa9264dae5/mmagic/models/editors/dreambooth/dreambooth.py#LL259C13-L259C18 
The `image` variable in this line is not used later, although it can be used, it may not be reasonable.

**Comment by LeoXing1996** [comment]
Hey @XDUWQ, `image` is used in https://github.com/open-mmlab/mmagic/blob/97f8a9b7a22dea71e629ba851d9d09aa9264dae5/mmagic/models/editors/dreambooth/dreambooth.py#L260, we calculate the clean latent code from `image`.
