### ISSUE TITLE
[Bug] component.py file in the GUI, it should be self.v2 instead of self.v1

### ISSUE THREAD

**Issue by Libyte** [open-mmlab/mmagic#1878]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

normal

### Reproduces the problem - code sample

normal

### Reproduces the problem - command or script

normal

### Reproduces the problem - error message

At line 442 of the component.py file in the GUI, it should be self.v2 instead of self.v1

**Comment by Z-Fran** [comment]
Thanks, we will fix it
