### ISSUE TITLE
[Feature] Load Pretrained Checkpoint to ControlNet

### ISSUE THREAD

**Issue by gvalvano** [open-mmlab/mmagic#1889]
### What's the feature?

I wish to load ControlNet pre-trained weights from local checkpoints rather than using `stable_diffusion_v15_url = 'runwayml/stable-diffusion-v1-5'`. Local checkpoints are the results of fine-tuning StableDiffusion and saving its weights locally. 

For example, one may train DreamBooth and then save the model after 10k iterations to the local machine, as `logs/iter_10000.pth`. Then, he may load such weights into ControlNet and train the model conditionally (see **TODO** below).

```python
stable_diffusion_v15_url = 'runwayml/stable-diffusion-v1-5'  # TODO: <-- change this to point to a local file "logs/iter_10000.pth" does not work!
controlnet_canny_url = 'lllyasviel/sd-controlnet-canny'

model = dict(
    type='ControlStableDiffusion',
    vae=dict(
        type='AutoencoderKL',
        from_pretrained=stable_diffusion_v15_url,
        subfolder='vae'),
    unet=dict(
        type='UNet2DConditionModel',
        subfolder='unet',
        from_pretrained=stable_diffusion_v15_url),
    text_encoder=dict(
        type='ClipWrapper',
        clip_type='huggingface',
        pretrained_model_name_or_path=stable_diffusion_v15_url,
        subfolder='text_encoder'),
    tokenizer=stable_diffusion_v15_url,
    controlnet=dict(
        type='ControlNetModel',
        # from_pretrained=controlnet_canny_url  # load pretrained
        from_config=controlnet_canny_url  # train from scratch
    ),
    scheduler=dict(
        type='DDPMScheduler',
        from_pretrained=stable_diffusion_v15_url,
        subfolder='scheduler'),
    test_scheduler=dict(
        type='DDIMScheduler',
        from_pretrained=stable_diffusion_v15_url,
        subfolder='scheduler'),
    data_preprocessor=dict(type='DataPreprocessor'),
    init_cfg=dict(type='init_from_unet'),
)

```

**Comment by gvalvano** [comment]
Any updates on this issue? :)

**Comment by gvalvano** [comment]
Hi @Z-Fran @LeoXing1996 Is there any activity going on/planned on this issue?

**Comment by Z-Fran** [comment]
> Hi @Z-Fran @LeoXing1996 Is there any activity going on/planned on this issue?

@gvalvano This feature is planned， but we need a few weeks to do it.

**Comment by valvgab-bh** [comment]
> > Hi @Z-Fran @LeoXing1996 Is there any activity going on/planned on this issue?
> 
> @gvalvano This feature is planned， but we need a few weeks to do it.

Thanks @Z-Fran :) if you can share a few hints about how to make it, I may give it a try myself

**Comment by gvalvano** [comment]
> > Hi @Z-Fran @LeoXing1996 Is there any activity going on/planned on this issue?
> 
> @gvalvano This feature is planned， but we need a few weeks to do it.

Thanks @Z-Fran :) if you can share a few hints about how to make it, I may give it a try myself

**Comment by Z-Fran** [comment]
@gvalvano  We are not sure how to resolve it now.
1. You can convert `iter_10000.pth` to diffusers model.  You can reference [this script](https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py). Note that you should build the MMagic model use:
```python
from mmagic.apis.inferencers.inference_functions import init_model
model = init_model(config='xxx',checkpoint='xxx')
```

2. MMagic use [CheckpointHook](https://github.com/open-mmlab/mmagic/blob/main/configs/_base_/gen_default_runtime.py#L19) from [mmengine](https://github.com/open-mmlab/mmengine/blob/main/mmengine/hooks/checkpoint_hook.py) to save model. You can modify it to save diffusers model. You can reference https://github.com/huggingface/diffusers/blob/61916fefc400d1b77171490b6ff7d53e509ed9de/src/diffusers/pipelines/pipeline_utils.py#L536  ,   https://github.com/huggingface/diffusers/blob/61916fefc400d1b77171490b6ff7d53e509ed9de/src/diffusers/models/modeling_utils.py#L275

**Comment by LeoXing1996** [comment]
Close due to no reponse. Please reopen it if you need more help.
