### ISSUE TITLE
[Bug] RuntimeError: The size of tensor a (260) must match the size of tensor b (257) at non-singleton dimension 3

### ISSUE THREAD

**Issue by jakhon37** [open-mmlab/mmagic#1902]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

with cpu: 
torch                                2.0.1+cpu
torchvision                          0.15.2+cpu

with gpu: 
python mmagic/utils/collect_env.py
sys.platform: linux
Python: 3.9.12 (main, Apr  5 2022, 06:56:58) [GCC 7.5.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2+cu117
OpenCV: 4.7.0
MMEngine: 0.7.4
MMCV: 2.0.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.7
MMagic: 1.0.1+55f5e44

### Reproduces the problem - code sample

python test.py 
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmediting/inpainting/global_local/gl_256x256_8x12_celeba_20200619-5af0493f.pth
06/13 22:25:48 - mmengine - WARNING - Failed to search registry with scope "mmagic" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmagic" is a correct scope, or whether the registry is initialized.
06/13 22:25:48 - mmengine - WARNING - `Visualizer` backend is not initialized because save_dir is None.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/jakhon37/myProjects/microservices/oracle_tm/in_paint/test.py:25 in <module>                │
│                                                                                                  │
│   22 # Create a MMagicInferencer instance and infer                                              │
│   23 result_out_dir = '../resources/output/inpainting/tutorial_inpainting_global_local_res.jp    │
│   24 editor = MMagicInferencer('global_local', model_setting=1)                                  │
│ ❱ 25 results = editor.infer(img=img, mask=mask, result_out_dir=result_out_dir)                   │
│   26                                                                                             │
│   27 # plot the result image                                                                     │
│   28 img = mmcv.imread(result_out_dir)                                                           │
│                                                                                                  │
│ /home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv/lib/python3.9/site-packages/mmagi │
│ c/apis/mmagic_inferencer.py:214 in infer                                                         │
│                                                                                                  │
│   211 │   │   │   Dict or List[Dict]: Each dict contains the inference result of                 │
│   212 │   │   │   each image or video.                                                           │
│   213 │   │   """                                                                                │
│ ❱ 214 │   │   return self.inferencer(                                                            │
│   215 │   │   │   img=img,                                                                       │
│   216 │   │   │   video=video,                                                                   │
│   217 │   │   │   label=label,                                                                   │
│                                                                                                  │
│ /home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv/lib/python3.9/site-packages/mmagi │
│ c/apis/inferencers/__init__.py:106 in __call__                                                   │
│                                                                                                  │
│   103 │   │   Returns:                                                                           │
│   104 │   │   │   Union[Dict, List[Dict]]: Results of inference pipeline.                        │
│   105 │   │   """                                                                                │
│ ❱ 106 │   │   return self.inferencer(**kwargs)                                                   │
│   107 │                                                                                          │
│   108 │   def get_extra_parameters(self) -> List[str]:                                           │
│   109 │   │   """Each inferencer may has its own parameters. Call this function to               │
│                                                                                                  │
│ /home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv/lib/python3.9/site-packages/torch │
│ /utils/_contextlib.py:115 in decorate_context                                                    │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ /home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv/lib/python3.9/site-packages/mmagi │
│ c/apis/inferencers/base_mmagic_inferencer.py:142 in __call__                                     │
│                                                                                                  │
│   139 │   │   postprocess_kwargs.update(params[3])                                               │
│   140 │   │                                                                                      │
│   141 │   │   data = self.preprocess(**preprocess_kwargs)                                        │
│ ❱ 142 │   │   preds = self.forward(data, **forward_kwargs)                                       │
│   143 │   │   imgs = self.visualize(preds, **visualize_kwargs)                                   │
│   144 │   │   results = self.postprocess(preds, imgs, **postprocess_kwargs)                      │
│   145 │   │   return results                                                                     │
│                                                                                                  │
│ /home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv/lib/python3.9/site-packages/mmagi │
│ c/apis/inferencers/inpainting_inferencer.py:61 in forward                                        │
│                                                                                                  │
│   58 │   │   """Forward the inputs to the model."""                                              │
│   59 │   │   inputs = self.model.data_preprocessor(inputs)                                       │
│   60 │   │   with torch.no_grad():                                                               │
│ ❱ 61 │   │   │   result = self.model(mode='predict', **inputs)                                   │
│   62 │   │   return result                                                                       │
│   63 │                                                                                           │
│   64 │   def visualize(self,                                                                     │
│                                                                                                  │
│ /home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv/lib/python3.9/site-packages/torch │
│ /nn/modules/module.py:1501 in _call_impl                                                         │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv/lib/python3.9/site-packages/mmagi │
│ c/models/base_models/one_stage.py:145 in forward                                                 │
│                                                                                                  │
│   142 │   │   │   return raw                                                                     │
│   143 │   │   elif mode == 'predict':                                                            │
│   144 │   │   │   # Pre-process runs in BaseModel.val_step / test_step                           │
│ ❱ 145 │   │   │   predictions = self.forward_test(inputs, data_samples)                          │
│   146 │   │   │   predictions = self.convert_to_datasample(predictions, data_samples,            │
│   147 │   │   │   │   │   │   │   │   │   │   │   │   │    inputs)                               │
│   148 │   │   │   return predictions                                                             │
│                                                                                                  │
│ /home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv/lib/python3.9/site-packages/mmagi │
│ c/models/base_models/one_stage.py:397 in forward_test                                            │
│                                                                                                  │
│   394 │   │   │   predictions (List[DataSample]): List of prediction saved in                    │
│   395 │   │   │   │   DataSample.                                                                │
│   396 │   │   """                                                                                │
│ ❱ 397 │   │   fake_reses, fake_imgs = self.forward_tensor(inputs, data_samples)                  │
│   398 │   │                                                                                      │
│   399 │   │   predictions = []                                                                   │
│   400 │   │   fake_reses = self.data_preprocessor.destruct(fake_reses, data_samples)             │
│                                                                                                  │
│ /home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv/lib/python3.9/site-packages/mmagi │
│ c/models/base_models/one_stage.py:382 in forward_tensor                                          │
│                                                                                                  │
│   379 │   │   masks = data_samples.mask  # N,1,H,W                                               │
│   380 │   │   input_xs = torch.cat([masked_imgs, masks], dim=1)  # N,4,H,W                       │
│   381 │   │   fake_reses = self.generator(input_xs)                                              │
│ ❱ 382 │   │   fake_imgs = fake_reses * masks + masked_imgs * (1. - masks)                        │
│   383 │   │   return fake_reses, fake_imgs                                                       │
│   384 │                                                                                          │
│   385 │   def forward_test(self, inputs: torch.Tensor,                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The size of tensor a (260) must match the size of tensor b (257) at non-singleton dimension 3

### Reproduces the problem - command or script

import mmcv
import matplotlib.pyplot as plt 
from mmagic.apis import MMagicInferencer

img = '/home/jakhon37/myProjects/microservices/oracle_tm/in_paint/data/test_im/celeba_test.png'
mask = '/home/jakhon37/myProjects/microservices/oracle_tm/in_paint/data/test_im/bbox_mask.png'
img = '/home/jakhon37/myProjects/microservices/oracle_tm/in_paint/data/image/m_new.jpg'
mask = '/home/jakhon37/myProjects/microservices/oracle_tm/in_paint/data/image/m_mask.jpg'

# show input image and mask
input_img = mmcv.imread(img)
plt.imshow(mmcv.bgr2rgb(input_img))
plt.show()
input_mask = mmcv.imread(mask)
plt.imshow(mmcv.bgr2rgb(input_mask))
plt.show()

# Create a MMagicInferencer instance and infer
result_out_dir = '../resources/output/inpainting/tutorial_inpainting_global_local_res.jpg'
editor = MMagicInferencer('global_local', model_setting=1)
results = editor.infer(img=img, mask=mask, result_out_dir=result_out_dir)

# plot the result image
img = mmcv.imread(result_out_dir)
plt.imshow(mmcv.bgr2rgb(img))
plt.show()

### Reproduces the problem - error message

│ /home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv/lib/python3.9/site-packages/mmagi │
│ c/models/base_models/one_stage.py:382 in forward_tensor                                          │
│                                                                                                  │
│   379 │   │   masks = data_samples.mask  # N,1,H,W                                               │
│   380 │   │   input_xs = torch.cat([masked_imgs, masks], dim=1)  # N,4,H,W                       │
│   381 │   │   fake_reses = self.generator(input_xs)                                              │
│ ❱ 382 │   │   fake_imgs = fake_reses * masks + masked_imgs * (1. - masks)                        │
│   383 │   │   return fake_reses, fake_imgs                                                       │
│   384 │                                                                                          │
│   385 │   def forward_test(self, inputs: torch.Tensor,                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The size of tensor a (260) must match the size of tensor b (257) at non-singleton dimension 3

### Additional information

1. original test image from mmagic repo runs fine 
but custom image and mask cannot run 
2. i resized the image and mask to 256x256 but still could not run 
3. i made image and mask size square but still could not run 
4.

**Comment by Z-Fran** [comment]
Could you please give us your test images to reimplement the bug?

**Comment by jakhon37** [comment]
First I tried to inpaint  image with different size of haight and width.  
I found all models run only with square size input images. 
I tried to add extra pixel to keep the image context as it was and do padding to make it square and new size was like 1499x1499. 
The model did not run. 
Then I added resizing code but it seems my code did not correctly resize image to certain size like 256x256 but resized to 257x257. (sorry about wrong report)
The model still did not run. 
I checked the source code as shown in the error but could no fix it. 
Then I reported it to you. 

Today I again check my code and properly resized to 256x256. 
It is finally running! 

The problem is: 
model cannot run images with the range 257:256+4 x 257:256+4.
so if the size is 257, 258, 259 it gives error as above.  
after size 260 it is the same error until size of 264. 

It seems model is changing the size while convolution operation. 

Is it possible to adjust the code so that it can take any size of image with any dimension(not only square size) and ouput with the same dimansion(not only square)?

**Comment by Z-Fran** [comment]
![image](https://github.com/open-mmlab/mmagic/assets/49083766/e9db02e9-d6d7-44b0-89c1-560c293198e2)
In the model, `H` and `W` should be multiples of 4.

**Comment by jakhon37** [comment]
Thank you for the clarification!

**Comment by jakhon37** [comment]
while doing colarization I could not find any detailed guide about input and tried it with single input 

I got the error below 
  File "/home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv_cuda/lib/python3.9/site-packages/mmagic/models/editors/inst_colorization/color_utils.py", line 200, in get_colorization_data
    data_lab = rgb2lab(data_raw, color_opt)
  File "/home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv_cuda/lib/python3.9/site-packages/mmagic/models/editors/inst_colorization/color_utils.py", line 181, in rgb2lab
    lab = xyz2lab(rgb2xyz(rgb))
  File "/home/jakhon37/myProjects/microservices/oracle_tm/mmagic/mmenv_cuda/lib/python3.9/site-packages/mmagic/models/editors/inst_colorization/color_utils.py", line 125, in rgb2xyz
    x = .412453 * rgb[:, 0, :, :] + .357580 * rgb[:, 1, :, :] \
IndexError: too many indices for tensor of dimension 3

I added if statement to the rgb2xyz function in color_utils.py as below and now it is working normally 

# "/my_env_cuda/lib/python3.9/site-packages/mmagic/models/editors/inst_colorization/color_utils.py"
def rgb2xyz(rgb):
    assert rgb.dim() == 3 or rgb.dim() == 4, "Unexpected dimensions for rgb tensor"

    if rgb.dim() == 3:
        rgb = rgb.unsqueeze(0)
    
    mask = (rgb > .04045).type(torch.FloatTensor)
    if (rgb.is_cuda):
        mask = mask.cuda()

    rgb = (((rgb + .055) / 1.055)**2.4) * mask + rgb / 12.92 * (1 - mask)

    x = .412453 * rgb[:, 0, :, :] + .357580 * rgb[:, 1, :, :] + .180423 * rgb[:, 2, :, :]
    y = .212671 * rgb[:, 0, :, :] + .715160 * rgb[:, 1, :, :] + .072169 * rgb[:, 2, :, :]
    z = .019334 * rgb[:, 0, :, :] + .119193 * rgb[:, 1, :, :] + .950227 * rgb[:, 2, :, :]

    out = torch.cat((x[:, None, :, :], y[:, None, :, :], z[:, None, :, :]), dim=1)

    if out.shape[0] == 1:  # if batch size is 1, squeeze it.
        out = out.squeeze(0)

    return out

**Comment by Z-Fran** [comment]
Try using the latest version.  https://github.com/open-mmlab/mmagic/pull/1901 This PR fix the bug.

**Comment by Z-Fran** [comment]
Closing this issue since the bug has been fixed in a merged pull request. Please feel free to reopen it if it has not been fixed.
