### ISSUE TITLE
[Bug] ‘demo/restoration_face_demo.py’ does not exist

### ISSUE THREAD

**Issue by yayoyo66** [open-mmlab/mmagic#1915]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

windows pytorch 1.12

### Reproduces the problem - code sample

I did not change any code

### Reproduces the problem - command or script

python demo/restoration_face_demo.py \
configs/glean/glean_in128out1024_4xb2-300k_ffhq-celeba-hq.py \
https://download.openmmlab.com/mmediting/restorers/glean/glean_in128out1024_4x2_300k_ffhq_celebahq_20210812-acbcb04f.pth \
tests/data/image/face/000001.png \
tests/data/pred/000001.png \
 --upscale-factor 4

### Reproduces the problem - error message

python: can't open file 'demo/restoration_face_demo.py': [Errno 2] No such file or directory

### Additional information

I wanted to try the example of 'Run a demo of facial restoration' in  'mmagic/docs/en/user_guides/inference.md', but got the error. 

I searched the 'Issues and Discussions' of MMagic, and found the 'restoration_face_demo.py' may exist in the past( link [inference error #616](https://github.com/open-mmlab/mmagic/issues/616) . But now, I cannot find it.

**Comment by Z-Fran** [comment]
It has been deprecated. Please mmagic v1.0.0rc7 https://github.com/open-mmlab/mmagic/tree/v1.0.0rc7

**Comment by Z-Fran** [comment]
Closing this issue since the bug has been fixed in a merged pull request. Please feel free to reopen it if it has not been fixed.
