### ISSUE TITLE
How to modify the configuration file when using styleganv2 to generate a single-channel 800x800 SAR image?

### ISSUE THREAD

**Issue by 19990101lrk** [open-mmlab/mmagic#1924]
### What's the feature?

I want to use the styleganv2 model to generate SAR images as a data enhancement method for other tasks. I have a single-channel 800x800 SAR image. How to modify the configuration file to generate the same single-channel SAR image. I am currently modifying the configuration file. The image size can only be 512x512 or 1024x1024 and the image is three-channel RGB.

**Comment by LeoXing1996** [comment]
@19990101lrk  Sorry for late response. To support 800x800 image, you can modify config as follow:
```diff
# model
model = dict(
-  generator=dict(out_size=512),
-  discriminator=dict(in_size=512),
+  generator=dict(out_size=800),
+  discriminator=dict(in_size=800),
    ema_config=dict(
        type='ExponentialMovingAverage',
        interval=1,
        momentum=1. - (0.5**(32. / (ema_half_life * 1000.)))),
    loss_config=dict(
        r1_loss_weight=10. / 2. * d_reg_interval,
        r1_interval=d_reg_interval,
        norm_mode='HWC',
        g_reg_interval=g_reg_interval,
        g_reg_weight=2. * g_reg_interval,
        pl_batch_shrink=2))
```

To train with single-scale image, you can manually convert you image from single channel to three channel by repeat it at color dimension, e.g.
```python
img = Image.open(img_path).convert('RGB')
```

**Comment by 19990101lrk** [comment]
> @19990101lrk Sorry for late response. To support 800x800 image, you can modify config as follow:
> 
> ```diff
> # model
> model = dict(
> -  generator=dict(out_size=512),
> -  discriminator=dict(in_size=512),
> +  generator=dict(out_size=800),
> +  discriminator=dict(in_size=800),
>     ema_config=dict(
>         type='ExponentialMovingAverage',
>         interval=1,
>         momentum=1. - (0.5**(32. / (ema_half_life * 1000.)))),
>     loss_config=dict(
>         r1_loss_weight=10. / 2. * d_reg_interval,
>         r1_interval=d_reg_interval,
>         norm_mode='HWC',
>         g_reg_interval=g_reg_interval,
>         g_reg_weight=2. * g_reg_interval,
>         pl_batch_shrink=2))
> ```
> 
> To train with single-scale image, you can manually convert you image from single channel to three channel by repeat it at color dimension, e.g.
> 
> ```python
> img = Image.open(img_path).convert('RGB')
> ```

Thank you for your answer, I will try to modify it.

**Comment by LeoXing1996** [comment]
Close due to no response. Please reopen if you need more help.
