### ISSUE TITLE
Is it possible to change default inference parameters from the config file?

### ISSUE THREAD

**Issue by gvalvano** [open-mmlab/mmagic#1925]
### What's the feature?

I wish to change how Stable Diffusion makes inference during its validation step. Basically, I would like to use a lower `guidance_scale` parameter in the [infer(.)](https://github.com/open-mmlab/mmagic/blob/1c932c024ccb88347618abfdfa61756f49646002/mmagic/models/editors/stable_diffusion/stable_diffusion.py#L165) function. I would like to set this behaviour during the validation step, in the `CheckpointHook`, so that I can save the best model based on the FID measured with that guidance scale:

```python
# hooks
default_hooks = dict(
    logger=dict(interval=NUM_ITER_PER_EPOCH),
    checkpoint=dict(
        type='CheckpointHook',
        by_epoch=False,
        interval=NUM_ITER_PER_EPOCH,
        save_optimizer=True,
        max_keep_ckpts=1,
        save_best=['FID-Full-50k/fid'], rule=['less'],
    )
)
```
The default guidance does not work well with my dataset, and I would like to set a lower `guidance_scale` just during the inference step so that I don't alter the training. Is this possible, or it requires a new feature?

**Comment by LeoXing1996** [comment]
Hi @gvalvano, sorry for late response.  We do not support this feature in current version of MMagic. 

In MMagic, each metrics get their own iterator durning evaluation by `get_metric_sampler`, e,g, 
https://github.com/open-mmlab/mmagic/blob/e5c0faa54b8cac8d0e3c92761c4c5ef4d0b55646/mmagic/evaluation/metrics/base_gen_metric.py#L253
and 
https://github.com/open-mmlab/mmagic/blob/e5c0faa54b8cac8d0e3c92761c4c5ef4d0b55646/mmagic/evaluation/metrics/fid.py#L267

Therefore, you can implement your own FID metric for Stable diffusion, and define a `get_metric_sampler` function which support pass guidance scale to `StableDiffusion.infer`.

**Comment by LeoXing1996** [comment]
Close due to no reponse. Please reopen it if you need more help.
