### ISSUE TITLE
[Feature] A convenient way to use '.safetensors' model

### ISSUE THREAD

**Issue by yayoyo66** [open-mmlab/mmagic#1926]
### What's the feature?

I want change the init model of stable diffusion and controlnet, but I find the 'from_pretrained' is default to read '.bin' model, and if the model is '.safetensors', it will report an error.

Therefore, I have to modify the source code in 'mmagic/models/archs/wrapper.py' to set 'use_safetensors=True'. If mmagic is not installed in source code, I have to reinstall it. I want a convenient way to use '.safetensors' model, because many models are now in this format. 

### Any other context?

Actually very simple, only need to add a parameter 'use_safetensors' when call  'DiffusersWrapper' class, but mmagic is super encapsulation that I can't find where the class is called.

**Comment by liuwenran** [comment]
Thanks for your advice. We will make "use_safetensors" available soon.
