### ISSUE TITLE
训练模型时提示警告The prefix is not set in metric class MAE[Bug] 

### ISSUE THREAD

**Issue by 11923303233** [open-mmlab/mmagic#1946]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

1

### Reproduces the problem - code sample

1

### Reproduces the problem - command or script

1

### Reproduces the problem - error message

1

**Comment by 11923303233** [comment]
警告还有warning div2k is not a meta file, simply parsed as meta information

**Comment by 11923303233** [comment]
我训练的是提供好的srcnn的代码，仅调整数据地址

**Comment by LeoXing1996** [comment]
Hi @11923303233, those warning will not hurt your training.

**Comment by 11923303233** [comment]
ok, I know. Thanks
