### ISSUE TITLE
请问模型推理怎么一张张保存推理结果呢？[Docs] 

### ISSUE THREAD

**Issue by sunyclj** [open-mmlab/mmagic#1947]
### Branch

main branch  https://mmagic.readthedocs.io/en/latest/

### 📚 The doc issue

请问模型推理怎么一张张保存推理结果呢？如realbasicvsr模型测试，

**Comment by LeoXing1996** [comment]
Hi @sunyclj , can you provide the config you used for training?
MMagic use `BasicVisualizationHook` to save visualization results during training.

**Comment by LeoXing1996** [comment]
Close due to no reponse. Please reopen if you need more help.

**Comment by Lipurple** [comment]
> Hi @sunyclj , can you provide the config you used for training? MMagic use `BasicVisualizationHook` to save visualization results during training.

Hi, could you tell me where I can modify the code for visualization? For example, for video super-resolution, what should I do if I want to save the result one image by one image, instead of concat them and save?
