### ISSUE TITLE
Test/Inference without metrics&gts

### ISSUE THREAD

**Issue by permanentCH5** [open-mmlab/mmagic#1951]
### What's the feature?

It is very difficult to use my trained model(swinir x4) to do super resolution on an image(or image list) without ground truth. I have to additionally create a fake ground truth before I use. Why should I must do super resolution with evaluation? I just want the image after super resolution.

**Comment by permanentCH5** [comment]
why no response

**Comment by liuwenran** [comment]
You could use mmagic inferencer to do inference. There are some demo cases in our notebook tutorial  [mmagic/demo/mmagic_inference_tutorial.ipynb](https://github.com/open-mmlab/mmagic/blob/main/demo/mmagic_inference_tutorial.ipynb) and super resolution is in section 4.4. If you want to do inference with your own model, you may need to write some codes in https://github.com/open-mmlab/mmagic/blob/main/mmagic/apis/mmagic_inferencer.py

**Comment by permanentCH5** [comment]
> You could use mmagic inferencer to do inference. There are some demo cases in mmagic notebook tutorial  [mmagic/demo/mmagic_inference_tutorial.ipynb](https://github.com/open-mmlab/mmagic/blob/main/demo/mmagic_inference_tutorial.ipynb) and super resolution is in section 4.4. If you want to do inference with your own model, you may need to write some codes in https://github.com/open-mmlab/mmagic/blob/main/mmagic/apis/mmagic_inferencer.py 

I know now. I have to do it all by myself. Many thanks.
