### ISSUE TITLE
[Bug] How to set random_seed

### ISSUE THREAD

**Issue by 11923303233** [open-mmlab/mmagic#1954]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

1

### Reproduces the problem - code sample

1

### Reproduces the problem - command or script

 1

### Reproduces the problem - error message

1

### Additional information

I want to compare the effect of different degradations on superresolution models. How to set the random seed to ensure that other contents are the same?

**Comment by zengyh1900** [comment]
hi @11923303233, 

You can set the random_seed in the config in `default_runtime.py`, e.g., https://github.com/open-mmlab/mmagic/blob/main/configs/_base_/gen_default_runtime.py#L3 

You can check more details about randomness in https://mmengine.readthedocs.io/en/latest/common_usage/set_random_seed.html

**Comment by 11923303233** [comment]
Thank you for your answer
