### ISSUE TITLE
[Bug] Controlnet weights are saved as 'controlnet.module.model...' but are indeed loaded as 'controlnet.model...'.

### ISSUE THREAD

**Issue by LoveU3tHousand2** [open-mmlab/mmagic#1959]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

...

### Reproduces the problem - code sample

Load_from in cfgfile or  load_checkpoint in inferencers.

### Reproduces the problem - command or script

...

### Reproduces the problem - error message

...

### Additional information

Alignment when saving and loading.

**Comment by LeoXing1996** [comment]
@LoveU3tHousand2, sorry for late response. You can convert your checkpoint files with the following script:
```python


```

**Comment by LeoXing1996** [comment]
@LoveU3tHousand2, sorry for late response. You can process the checkpoint file with the following script:
```python
import torch

new_model_dict = dict()
state_dict = torch.load(CHECKPOINT)
model_dict = state_dict['model']

for k, v in model_dict.items():
    if k.startswith('controlnet'):
        new_k = k.replace('module.', '')
        new_model_dict[new_k] = v
    else:
        new_model_dict[k] = v

state_dict['model'] = new_model_dict
```

**Comment by LoveU3tHousand2** [comment]
Thanks for response. I already did it.

Sent from my iPhone

On Jul 31, 2023, at 11:22, LeoXing1996 ***@***.***> wrote:

﻿

@LoveU3tHousand2<https://github.com/LoveU3tHousand2>, sorry for late response. You can process the checkpoint file with the following script:

import torch

new_model_dict = dict()
state_dict = torch.load(CHECKPOINT)
model_dict = state_dict['model']

for k, v in model_dict.items():
    if k.startswith('controlnet'):
        new_k = k.replace('module.', '')
        new_model_dict[new_k] = v
    else:
        new_model_dict[k] = v

state_dict['model'] = new_model_dict
